// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPsAvVhiQaJun1rdtDxaWrojAYwJhqH2I',
    appId: '1:55000417183:web:374d399c05ab3c8ff5b3aa',
    messagingSenderId: '55000417183',
    projectId: 'ecommerce-bd9cc',
    authDomain: 'ecommerce-bd9cc.firebaseapp.com',
    storageBucket: 'ecommerce-bd9cc.firebasestorage.app',
    measurementId: 'G-BX4FM7P51J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtc0OUNz8YA0hEpNWigz22m1r3P6-B4FY',
    appId: '1:55000417183:android:b07f17bba5ae92b3f5b3aa',
    messagingSenderId: '55000417183',
    projectId: 'ecommerce-bd9cc',
    storageBucket: 'ecommerce-bd9cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATeA3VGFRiCOvCWLRGghA1Wc9hS7VoDyQ',
    appId: '1:55000417183:ios:685dc8af4ec52bd1f5b3aa',
    messagingSenderId: '55000417183',
    projectId: 'ecommerce-bd9cc',
    storageBucket: 'ecommerce-bd9cc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClothes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATeA3VGFRiCOvCWLRGghA1Wc9hS7VoDyQ',
    appId: '1:55000417183:ios:685dc8af4ec52bd1f5b3aa',
    messagingSenderId: '55000417183',
    projectId: 'ecommerce-bd9cc',
    storageBucket: 'ecommerce-bd9cc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClothes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPsAvVhiQaJun1rdtDxaWrojAYwJhqH2I',
    appId: '1:55000417183:web:49e8acb9e2d222c1f5b3aa',
    messagingSenderId: '55000417183',
    projectId: 'ecommerce-bd9cc',
    authDomain: 'ecommerce-bd9cc.firebaseapp.com',
    storageBucket: 'ecommerce-bd9cc.firebasestorage.app',
    measurementId: 'G-FJLJ3FKV3K',
  );
}
